base/urls.py
from django.urls import path
from . import views

# Импорты для отображения профлильных фото на локальном сервере
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.home_page, name="home"),
    path('compare/', views.compare_page, name="compare_page"),

    path('login/', views.login_page, name="login_page"),
    path('logout/', views.logoutUser, name="logout"),
    path('delete/<str:pk>/', views.delete_profile, name="delete_profile"),

    path('sportman-profile/<str:pk>/', views.sportmanProfile, name="sportman-profile"),
    path('edit-profile/<str:pk>/', views.sportmanProfile, name="edit-profile"),
    path('sportman-profile/anthropometry/<str:pk>', views.sportmanAnthropometry, name="sportman-anthropometry"),
    path('sportman-profile/competitions/<str:pk>', views.sportmanCompetitions, name="sportman-competitions"),
    path('sportman-profile/career/<str:pk>', views.sportmanCareer, name="sportman-career"),
    path('sportman-profile/indicators/<str:pk>', views.sportmanIndicators, name="sportman-indicators"),
    path('sportman-profile/medicine/<str:pk>', views.sportmanMedicine, name="sportman-medicine"),
    path('sportman-profile/diet/<str:pk>', views.sportmanDiet, name="sportman-diet"),
    path('sportman-profile/traumas/<str:pk>', views.sportmanTrauma, name="sportman-traumas"),
]

# Условие для отображения картинкок из бд на локальном сервере
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spartak/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls'))
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

class Sportsman(models.Model):
    name = models.CharField(max_length=50)
    second_name = models.CharField(max_length=50)
    parent_name = models.CharField(max_length=50)
    birthday = models.DateField()
    phone_number = models.CharField(max_length=12)
    address = models.CharField(max_length=300, null=True, blank=True)
    passport = models.CharField(max_length=20)
    photo = models.ImageField(null=True, blank=True, upload_to="sportmen-images/", verbose_name="Изображение")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Anthropometry(models.Model):
    sportman = models.ForeignKey(Sportsman, on_delete=models.CASCADE, null=True)
    height = models.FloatField()
    weight = models.FloatField()
    index = models.FloatField(blank=True, null=True)
    time = models.DateField()

    def __str__(self):
        return f'Anthropometry: {self.sportman.name} {self.sportman.second_name} {self.sportman.parent_name}'

class Competitions(models.Model):
    sportman = models.ForeignKey(Sportsman, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    result = models.CharField(max_length=100)
    time = models.DateField()

    def __str__(self):
        return f'Competition: {self.sportman.name} {self.sportman.second_name} {self.sportman.parent_name} | {self.name}'

class Career(models.Model):
    sportman = models.ForeignKey(Sportsman, on_delete=models.SET_NULL, null=True)
    team_name = models.CharField(max_length=200)
    position = models.CharField(max_length=200)
    start = models.DateField()
    end = models.DateField()

    def __str__(self):
        return f'Career: {self.sportman.name} {self.sportman.second_name} {self.sportman.parent_name} | {self.start}-{self.end}'

class Indicators(models.Model):

    INDICATOR_CHOISES = [
        ('Подтягивания на перекладине (кол-во)', 'Подтягивания на перекладине (кол-во)'),
        ('Тройной прыжок с места (см)', 'Тройной прыжок с места (см)'),
        ('Пятикратный прыжок (см)', 'Пятикратный прыжок (см)'),
        ('Поднимание туловища 60 сек. (кол-во)', 'Поднимание туловища 60 сек. (кол-во)'),
        ('Бег 60м (сек)', 'Бег 60м (сек)'),
        ('Бег 300м (сек)', 'Бег 300м (сек)'),
        ('Бег 3000м (мин)', 'Бег 3000м (мин)'),
        ('Бег на коньках 36м лицом вперед (сек)', 'Бег на коньках 36м лицом вперед (сек)'),
        ('Бег на коньках 36м спиной вперед (сек)', 'Бег на коньках 36м спиной вперед (сек)'),
        ('Челночный бег на коньках 18 х 12 м (сек)', 'Челночный бег на коньках 18 х 12 м (сек)'),
        ('8-минутный бег на коньках (км)', '8-минутный бег на коньках (км)'),
        ('Точность бросков шайбы в цель (очки)', 'Точность бросков шайбы в цель (очки)'),
    ]

    sportman = models.ForeignKey(Sportsman, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=300, choices=INDICATOR_CHOISES, default='Бег 60м (сек)')
    result = models.CharField(max_length=100)
    time = models.DateField()

    def __str__(self):
        return f'Indicator: {self.sportman.name} {self.sportman.second_name} {self.sportman.parent_name} | {self.name}'

class Medicine(models.Model):
    sportman = models.ForeignKey(Sportsman, on_delete=models.SET_NULL, null=True)
    bpm = models.IntegerField(blank=True, null=True)
    arterial_pressure = models.CharField(max_length=7, blank=True, null=True)
    medical_tests = models.FileField(blank=True, null=True)
    medical_survey = models.FileField(blank=True, null=True)
    time = models.DateField()

    def __str__(self):
        return f'Indicator: {self.sportman.name} {self.sportman.second_name} {self.sportman.parent_name} | {self.time}'

class Product(models.Model):
    name = models.CharField(max_length=100)
    proteins = models.FloatField(max_length=10)
    fats = models.FloatField(max_length=10)
    carbo = models.FloatField(max_length=10)
    calories = models.FloatField(max_length=10)

    def __str__(self):
        return f'{self.name} | {self.calories}'


class Diet(models.Model):
    sportman = models.ForeignKey(Sportsman, on_delete=models.SET_NULL, null=True)
    monday_breakfast = models.TextField(null=True, blank=True)
    monday_lunch = models.TextField(null=True, blank=True)
    monday_dinner = models.TextField(null=True, blank=True)
    monday_calories = models.CharField(max_length=100, null=True, blank=True)
    
    tuesday_breakfast = models.TextField(null=True, blank=True)
    tuesday_lunch = models.TextField(null=True, blank=True)
    tuesday_dinner = models.TextField(null=True, blank=True)
    tuesday_calories = models.CharField(max_length=100, null=True, blank=True)

    wednesday_breakfast = models.TextField(null=True, blank=True)
    wednesday_lunch = models.TextField(null=True, blank=True)
    wednesday_dinner = models.TextField(null=True, blank=True)
    wednesday_calories = models.CharField(max_length=100, null=True, blank=True)
    
    thursday_breakfast = models.TextField(null=True, blank=True)
    thursday_lunch = models.TextField(null=True, blank=True)
    thursday_dinner = models.TextField(null=True, blank=True)
    thursday_calories = models.CharField(max_length=100, null=True, blank=True)

    friday_breakfast = models.TextField(null=True, blank=True)
    friday_lunch = models.TextField(null=True, blank=True)
    friday_dinner = models.TextField(null=True, blank=True)
    friday_calories = models.CharField(max_length=100, null=True, blank=True)

    saturday_breakfast = models.TextField(null=True, blank=True)
    saturday_lunch = models.TextField(null=True, blank=True)
    saturday_dinner = models.TextField(null=True, blank=True)
    saturday_calories = models.CharField(max_length=100, null=True, blank=True)
    
    sunday_breakfast = models.TextField(null=True, blank=True)
    sunday_lunch = models.TextField(null=True, blank=True)
    sunday_dinner = models.TextField(null=True, blank=True)
    sunday_calories = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return f'{self.sportman.name}'

class Trauma(models.Model):
    sportman = models.ForeignKey(Sportsman, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    file = models.FileField(blank=True, null=True)
    start = models.DateField()
    end = models.DateField()

    def __str__(self):
        return f'{self.name} | {self.start} - {self.end}'

templates/compare.html
{% extends 'main_profile.html' %}
{% load static %}

{% block content %}

<div class="compare__content">
    
    <div class="compare__header">
        <div class="compare__title">
            <h2>Сравнить спортсменов</h2>
        </div>
        <div class="compare__submit-form">
            <form action="{% url 'compare_page' %}" method="POST">
                {% csrf_token %}
                <div class="form-compare">
                    <div class="input-text">
                        <input type="text" name="left-sportman">
                    </div>

                    <div class="input-button">
                        <input type="submit" value="Сравнить">
                    </div>

                    <div class="input-text">
                        <input type="text" name="right-sportman">
                    </div>
                </div>
            </form> 
        </div>
    </div>
    <!-- Блок со спортсменами -->
    {% if left_sportman is not None and right_sportman is not None %}
    <div class="compare__sportmans">




        <!-- Левый спортсмен для сравнения -->
        <div class="compare__left  left-sportman">
            <div class="left-sportman__header">
                <a href="{% url 'sportman-profile' left_sportman.id %}">
                    <h2 class="left-sportman__name">{{left_sportman.name}} {{left_sportman.second_name}} {{left_sportman.parent_name}}</h2>
                </a>
            </div>

            <div class="left-sportman__body">
                <!-- Антропометрия -->
                <div class="left-sportman__anthropometry">
                    <div class="left-sportman__anthropometry__title">
                        <h3>Антропометрия</h3>
                    </div>
                    <div class="anthropometry__row anthropometry__header">
                        <div class="sportmanRow__right anthropometry__header__right">
                            <h4>Рост</h4>
                            <h4>Вес</h4>
                            <div class="anthropometry__time anthropometry__header__time__compare">Дата измерения</div>
                        </div>
                    </div>
                    {% for anthropometry in left_sportman_anthropometry %}
                    <div class="anthropometry__row">
                        <div class="sportmanRow__right">
                            <h4>{{anthropometry.height}}см</h4>
                            <h4>{{anthropometry.weight}}кг</h4>
                            <div class="anthropometry__time__compare">{{anthropometry.time|date:'d.m.Y'}}</div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

                <!-- Карьерная история -->
                <div class="left-sportman__career">
                    <div class="left-sportman__career__title">
                        <h3>Карьерная история</h3>
                    </div>
                    {% for career in left_sportman_career %}
                        <div class="career__body">
                            <hr>
                            <div>Название команды: {{career.team_name}}</div>
                            <div>Позиция на льду: {{career.position}}</div>
                            <div>Срок работы в клубе: {{career.start|date:'d.m.Y'}}-{{career.end|date:'d.m.Y'}}</div>
                        </div>
                    {% endfor %}
                </div>

                <!-- Нормативы -->
                <div class="left-sportman__career">
                    <div class="left-sportman__career__title">
                        <h3>Нормативы</h3>
                    </div>
                    {% for indicator in left_sportman_indicators %}
                        <div class="career__body">
                            <hr>
                            <div>Норматив: {{indicator.name}}</div>
                            <div>Результат: {{indicator.resault}}</div>
                            <div>Дата замера: {{indicator.time|date:'d.m.Y'}}</div>
                        </div>
                    {% endfor %}
                </div>


            </div>
        </div>




        <!-- Правый спортсмен для сравнения -->
        <div class="compare__right right-sportman">
            <div class="right-sportman__header">
                <a href="{% url 'sportman-profile' right_sportman.id %}">
                    <h2 class="right-sportman__name">{{right_sportman.name}} {{right_sportman.second_name}} {{right_sportman.parent_name}}</h2>
                </a>
            </div>

            <div class="right-sportman__body">
                <div class="right-sportman__anthropometry">
                    <div class="right-sportman__anthropometry__title">
                        <h3>Антропометрия</h3>
                    </div>
                    <div class="anthropometry__row anthropometry__header">
                        <div class="sportmanRow__right anthropometry__header__right">
                            <h4>Рост</h4>
                            <h4>Вес</h4>
                            <div class="anthropometry__time anthropometry__header__time__compare">Дата измерения</div>
                        </div>
                    </div>
                    {% for anthropometry in right_sportman_anthropometry %}
                        <div class="anthropometry__row">
                            <div class="sportmanRow__right">
                                <h4>{{anthropometry.height}}см</h4>
                                <h4>{{anthropometry.weight}}кг</h4>
                                <div class="anthropometry__time__compare">{{anthropometry.time|date:'d.m.Y'}}</div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <!-- Карьерная история -->
                <div class="left-sportman__career">
                    <div class="left-sportman__career__title">
                        <h3>Карьерная история</h3>
                    </div>
                    {% for career in right_sportman_career %}
                        <div class="career__body">
                            <hr>
                            <div>Название команды: {{career.team_name}}</div>
                            <div>Позиция на льду: {{career.position}}</div>
                            <div>Срок работы в клубе: {{career.start|date:'d.m.Y'}}-{{career.end|date:'d.m.Y'}}</div>
                        </div>
                    {% endfor %}
                </div>

                <!-- Нормативы -->
                <div class="left-sportman__career">
                    <div class="left-sportman__career__title">
                        <h3>Нормативы</h3>
                    </div>
                    {% for indicator in right_sportman_indicators %}
                        <div class="career__body">
                            <hr>
                            <div>Норматив: {{indicator.name}}</div>
                            <div>Результат: {{indicator.resault}}</div>
                            <div>Дата замера: {{indicator.time|date:'d.m.Y'}}</div>
                        </div>
                    {% endfor %}
                </div>


            </div>
        </div>

    </div>
    {% endif %}
</div>

{% endblock content %}

templates/home.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
<!-- Sportmans List Starts -->
<div class="sportmanList">
    <div class="sportmanList_list">

        {% for sportman in sportmans %}
            <div class="sportmanRow">
                <div class="sportmanRow__left">
                    <div class="sportmanRow__options">
                        <a href="{% url 'delete_profile' sportman.id %}">
                            <span class="material-symbols-outlined material-symbols-outlined__delete">
                                delete
                            </span>
                        </a>
                        <span class="material-symbols-outlined material-symbols-outlined__document">
                            document_scanner
                        </span>
                        <a href="{% url 'edit-profile' sportman.id %}">
                            <span class="material-symbols-outlined material-symbols-outlined__edit">
                                edit
                            </span>
                        </a>
                    </div>
                    <a href="{% url 'sportman-profile' sportman.id %}">
                        <h3 class="sportmanRow__title">{{sportman.second_name}} {{sportman.name}} {{sportman.parent_name}}</h3>
                    </a>
                </div>
                
                <div class="sportmanRow__right">
                    <h4 class="sportmanRow__birthday">{{sportman.birthday|date:'d.m.Y'}}</h4>
                    <h4 class="sportmanRow__telNumber">{{sportman.phone_number}}</h4>
                    <h4 class="sportmanRow__id">{{sportman.id}}</h4>
                    <div class="sportmanRow__time">{{sportman.created|date:'d.m.Y H:i'}}</div>
                </div>
            </div>
        {% endfor %}
        
    </div>
</div>
<!-- Sportmans List Ends -->
{% endblock content %}

templates/login_page.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Спартак</title>
    <link rel="stylesheet" href="{% static 'css/login_page.css' %}">
    <!-- Google Font Icons -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
</head>
<body> 

    <div class="container">
        <div class="form">
            <span class="title">Вход</span>

            <form method="POST">
                {% csrf_token %}
                <div class="input_field">
                    <input type="text" placeholder="Логин" name="username">
                    <span class="material-symbols-outlined icon">
                        mail
                    </span>
                </div>

                <div class="input_field">
                    <input type="password" placeholder="Пароль" name="password">
                    <span class="material-symbols-outlined icon">
                        lock
                    </span>
                    <span class="material-symbols-outlined eye">
                        visibility_off
                    </span>
                </div>
                
                <div class="input_field button">
                    <input type="submit" value="Войти">
                </div>
            </form>
        </div>
    </div>
    
</body>
</html>

<!-- <form action="" method="POST">
    {% csrf_token %}

    <div class="field email-field">
        <div class="input-field">
            <input type="text" placeholder="Логин" class="email" name="username" />
        </div>
        <span class="error email-error">
            <i class="bx bx-error-circle error-icon"></i>
            <p class="error-text">Please enter a valid email</p>
        </span>
        </div>

        <div class="field create-password">
        <div class="input-field">
            <input
            type="password"
            placeholder="Пароль"
            class="password"
            name="password"
            />
            <i class="bx bx-hide show-hide"></i>
        </div>
        <span class="error password-error">
            <i class="bx bx-error-circle error-icon"></i>
            <p class="error-text">
            Please enter atleast 8 charatcer with number, symbol, small and
            capital letter.
            </p>
        </span>
        </div>

        <div class="input-field button">
        <input type="submit" value="Войти" />
        </div>
</form> -->

templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Google Font Icons -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />

    <!-- CSS Styles -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/main_profile.css' %}">

    <title>Спартак</title>
</head>
<body>
    <!-- Header Starts -->
    <header class="header">
        <div class="header__left">
            
        </div>

        <div class="header__middle">
            <span class="material-symbols-outlined">
                search
            </span>
            <form action="{% url 'home' %}" method="GET">
                <input type="text" placeholder="Поиск по цифровым профилям" name="q">
            </form>
        </div>

        <div class="header__right">
            <a href="{% url 'logout' %}">
                <button class="sidebar__compose logout__button">
                    Выйти
                </button>
            </a>
        </div>
    </header>
    <!-- Header Ends -->

    <!-- Main Body Starts -->

    <div class="main__body">

        <!-- Sidebar Starts -->

        <div class="sidebar">
            <a href="#create_popup" class="popup-link">
                <div class="sidebar__compose">
                    <span class="material-symbols-outlined">
                        add
                    </span>
                    Добавить
                </div>
            </a>

            <a href="{% url 'home' %}">
                <div class="sidebarOption sidebarOption__active">
                    <span class="material-symbols-outlined">
                        list_alt
                    </span>
                    <h3>Список спортсменов</h3>
                </div>
            </a>

            <a href="{% url 'compare_page' %}">
                <div class="sidebarOption">
                    <span class="material-symbols-outlined">
                        insert_chart
                    </span>
                    <h3>Сравнить данные</h3>
                </div>
            </a>

            <div class="sidebarOption">
                <span class="material-symbols-outlined">
                    lunch_dining
                </span>
                <h3>Сравнить системы питания</h3>
            </div>

            <div class="sidebarOption">
                <span class="material-symbols-outlined">
                    delete
                </span>
                <h3>Корзина</h3>
            </div>
            
        </div>

        <!-- Sidebar Ends -->

        {% block content %}
        
        {% endblock content %}

    </div>

    <!-- Main Body Ends -->

    <!-- Pop-up Create a digital profile Starts -->
    <div class="popup" id="create_popup">
        <div class="popup__body">
            <div class="popup__content">
                <a href="/" class="popup__close close-popup">
                    <span class="material-symbols-outlined">
                        close
                    </span>
                </a>
                <div class="popup__title">Добавить спортсмена</div>
                    <div class="form">
                        <form action="/" method="POST">
                            {% csrf_token %}
                            <div class="input_field">
                                {{sportman_form.name}}
                            </div>

                            <div class="input_field">
                                {{sportman_form.second_name}}
                            </div>

                            <div class="input_field">
                                {{sportman_form.parent_name}}
                            </div>

                            <div class="input_field">
                                {{sportman_form.birthday}}
                            </div>
                            
                            <div class="input_field">
                                {{sportman_form.phone_number}}
                            </div>
                            
                            <div class="input_field">
                                {{sportman_form.passport}}
                            </div>
                            
                            <div class="input_field button">
                                <input type="submit" value="Добавить">
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Pop-up Create a digital profile Ends -->
    <script src="{% static 'js/sidebar.js' %}"></script>
</body>
</html>

templates/main_profile.html
{% extends 'main_not_form.html' %}
{% load static %}

{% block content %}

{% endblock content %}

templates/profile.html
{% extends 'main_profile.html' %}
{% load static %}

{% block content %}

<div class="sportmanList profileBody">
    <!-- Контент профиля -->
    <div class="profile__content">
        <div class="profile__inf">
            <div class="profile__inf__title">
                <h3 class="profile__id">id: {{sportman.id}}</h3>
                <h3 class="profile__title">Цифровой профиль: Общая информация</h3>
            </div>
            <div class="profile_inf__content">
                <div class="profile__form">
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form__input">
                            <label class="label_field">Имя:</label>
                            <div class="profile_input_field">
                                {{sportman_form.name}}
                            </div>
                        </div>
        
                        <div class="form__input">
                            <label class="label_field">Фамилия:</label>
                            <div class="profile_input_field">
                                {{sportman_form.second_name}}
                            </div>
                        </div>
        
                        <div class="form__input">
                            <label class="label_field">Отчество:</label>
                            <div class="profile_input_field">
                                {{sportman_form.parent_name}}
                            </div>
                        </div>
        
                        <div class="form__input">
                            <label class="label_field">Дата рождения:</label>
                            <div class="profile_input_field">
                                {{sportman_form.birthday}}
                            </div>
                        </div>
                        
                        <div class="form__input">
                            <label class="label_field">Номер телефона:</label>
                            <div class="profile_input_field">
                                {{sportman_form.phone_number}}
                            </div>
                        </div>
        
                        <div class="form__input">
                            <label class="label_field">Адрес:</label>
                            <div class="profile_input_field">
                                {{sportman_form.address}}
                            </div>
                        </div>
                        
                        <div class="form__input">
                            <label class="label_field">Паспорт:</label>
                            <div class="profile_input_field">
                                {{sportman_form.passport}}
                            </div>
                        </div>
                        
                        <div class="form__input">
                            <label class="label_field">Фото:</label>
                            <div class="profile_input_field">
                                <input id="id_photo" type="file" accept="image/*" name="photo">
                            </div>
                        </div>
                    
                        <div class="input_field button_profile">
                            <input type="submit" value="Сохранить">
                        </div>
                    </form>
                </div>
                <div class="profile__photo">
                    {% if sportman.photo.url != 'Null'%}
                        <img src='{{MEDIA_URL}}{{sportman.photo.url}}' alt="">
                    {% else %}
                        <img src="/media/sportmen-images/profile-unknown-male.jpg" alt="">
                    {% endif %}
                    <div class="photo__edit">
                        <div class="photo__delete">
                            Удалить
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Sidebar профиля -->
    <div class="profile__sidebar">
        <a href="{% url 'sportman-profile' sportman.id %}">
            <div class="profile__sidebarOption profile__sidebarOption_active">
                <h3>Общая информация</h3>
            </div>
        </a>
        <a href="{% url 'sportman-anthropometry' sportman.id %}">
            <div class="profile__sidebarOption">
                <h3>Антропометрия</h3>
            </div>
        </a> 
        <a href="{% url 'sportman-career' sportman.id %}">
            <div class="profile__sidebarOption">
                <h3>Карьерная история</h3>
            </div>
        </a>
        <a href="{% url 'sportman-medicine' sportman.id %}">
            <div class="profile__sidebarOption">
                <h3>Медицинские показатели</h3>
            </div>
        </a>
        <a href="{% url 'sportman-indicators' sportman.id %}">
            <div class="profile__sidebarOption">
                <h3>Нормативы</h3>
            </div>
        </a>
        <a href="{% url 'sportman-competitions' sportman.id %}">
            <div class="profile__sidebarOption">
                <h3>История соревнований</h3>
            </div>
        </a>
        <a href="{% url 'sportman-diet' sportman.id %}">
            <div class="profile__sidebarOption">
                <h3>Система питания</h3>
            </div>
        </a>
        <a href="{% url 'sportman-traumas' sportman.id %}">
            <div class="profile__sidebarOption">
                <h3>Травмы</h3>
            </div>
        </a>
    </div>
</div>

{% endblock content %}